#!/usr/bin/env python3
"""Build bundler: stitch the baseline/ package into one self-contained
zappy_ai executable.

The source is split into clear modules (net, gather, manifest, ...) for
readability, but the deliverable must be a single file (the Makefile copies one
zappy_ai to the repo root). This script concatenates the modules in dependency
order, dropping the internal ``from .`` imports (everything lands in one
namespace) and hoisting+deduping the stdlib imports to the top.

Usage: python3 baseline/_bundle.py > zappy_ai
"""

import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Concatenation order: leaves first, then mixins, then the AI class that
# inherits them, then the training shims, then the CLI entrypoint (which must
# stay last so the ``__main__`` guard runs after everything is defined).
ORDER = [
    "constants.py",
    "models.py",
    "net.py",
    "protocol.py",
    "sensing.py",
    "movement.py",
    "behaviors.py",
    "gather.py",
    "manifest.py",
    "census.py",
    "brain.py",
    "ai.py",
    "shims.py",
    "cli.py",
]

SHEBANG = "#!/usr/bin/env python3"


def split_module(text: str):
    """Return (stdlib import lines, body without imports).

    Imports are detected via the AST (never by line heuristics — a docstring
    line can legitimately start with "from " or "import "). Relative imports
    ("from .net import ...") are internal cross-module wiring and dropped; the
    bundle is one flat namespace. Absolute imports are stdlib -> hoisted.
    """
    tree = ast.parse(text)
    lines = text.splitlines()
    drop = set()  # 1-based line numbers belonging to top-level import statements
    imports = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for ln in range(node.lineno, node.end_lineno + 1):
                drop.add(ln)
            internal = isinstance(node, ast.ImportFrom) and (node.level or 0) > 0
            if not internal:
                imports.append(ast.get_source_segment(text, node))
    body = [
        ln
        for i, ln in enumerate(lines, 1)
        if i not in drop and not (i == 1 and ln.startswith("#!"))
    ]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return imports, "\n".join(body)


def main() -> int:
    all_imports = set()
    bodies = []
    for name in ORDER:
        path = os.path.join(HERE, name)
        with open(path) as f:
            imports, body = split_module(f.read())
        all_imports.update(imports)
        bodies.append((name, body))

    out = []
    out.append(SHEBANG)
    out.append("")
    out.append("# ============================================================")
    out.append("# AUTO-GENERATED by baseline/_bundle.py — DO NOT EDIT.")
    out.append("# Edit the modules in baseline/ and run `make` to rebuild.")
    out.append("# ============================================================")
    out.append("")
    for imp in sorted(all_imports):
        out.append(imp)
    out.append("")
    for name, body in bodies:
        out.append("")
        out.append(f"# ---- {name} " + "-" * (66 - len(name)))
        out.append("")
        out.append(body)
        out.append("")
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
