#!/usr/bin/env python3

# ============================================================
# AUTO-GENERATED by baseline/_bundle.py — DO NOT EDIT.
# Edit the modules in baseline/ and run `make` to rebuild.
# ============================================================

from dataclasses import dataclass, field
from typing import Dict
from typing import Dict, List
from typing import Dict, List, Optional, Tuple
from typing import List, Optional
from typing import List, Optional, Tuple
from typing import Optional
import argparse
import enum
import os
import random
import select
import signal
import socket
import subprocess
import sys
import time


# ---- constants.py ------------------------------------------------------

"""Game constants: resources, stones, incantation requirements."""

RESOURCES = ["food", "linemate", "deraumere", "sibur", "mendiane", "phiras", "thystame"]

STONES = ["linemate", "deraumere", "sibur", "mendiane", "phiras", "thystame"]


REQ = {
    1: {
        "players": 1,
        "linemate": 1,
        "deraumere": 0,
        "sibur": 0,
        "mendiane": 0,
        "phiras": 0,
        "thystame": 0,
    },
    2: {
        "players": 2,
        "linemate": 1,
        "deraumere": 1,
        "sibur": 1,
        "mendiane": 0,
        "phiras": 0,
        "thystame": 0,
    },
    3: {
        "players": 2,
        "linemate": 2,
        "deraumere": 0,
        "sibur": 1,
        "mendiane": 0,
        "phiras": 2,
        "thystame": 0,
    },
    4: {
        "players": 4,
        "linemate": 1,
        "deraumere": 1,
        "sibur": 2,
        "mendiane": 0,
        "phiras": 1,
        "thystame": 0,
    },
    5: {
        "players": 4,
        "linemate": 1,
        "deraumere": 2,
        "sibur": 1,
        "mendiane": 3,
        "phiras": 0,
        "thystame": 0,
    },
    6: {
        "players": 6,
        "linemate": 1,
        "deraumere": 2,
        "sibur": 3,
        "mendiane": 0,
        "phiras": 1,
        "thystame": 0,
    },
    7: {
        "players": 6,
        "linemate": 2,
        "deraumere": 2,
        "sibur": 2,
        "mendiane": 2,
        "phiras": 2,
        "thystame": 1,
    },
}


# ---- models.py ---------------------------------------------------------

"""State machine enum + per-bot Memory model."""




class State(enum.Enum):
    SURVIVE = "SURVIVE"
    LOOK = "LOOK"
    COLLECT = "COLLECT"
    EXPLORE = "EXPLORE"
    FARM_FOOD = "FARM_FOOD"
    CALL_TEAMMATES = "CALL_TEAMMATES"
    PREPARE_INCANTATION = "PREPARE_INCANTATION"
    INCANT = "INCANT"
    REPRODUCE = "REPRODUCE"
    DEAD = "DEAD"


@dataclass
class Memory:
    width: int = 0
    height: int = 0
    free_slots: int = 0
    level: int = 1
    inventory: Dict[str, int] = field(default_factory=lambda: {r: 0 for r in RESOURCES})
    visible_tiles: List[List[str]] = field(default_factory=list)
    inventory_dirty: bool = True
    force_look: bool = False
    was_ejected: bool = False
    actions_since_inventory: int = 0
    moves_since_look: int = 0
    last_inventory_at: float = 0.0
    last_look_at: float = 0.0
    last_fork_at: float = 0.0
    forks_done: int = 0
    last_gather_at: float = 0.0


# ---- net.py ------------------------------------------------------------

"""NetMixin: net responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class NetMixin:
    def connect(self) -> None:
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.connect((self.host, self.port))
        self.sock.setblocking(False)

    def send_raw(self, line: str) -> None:
        if not self.sock:
            raise RuntimeError("socket not connected")
        if not line.endswith("\n"):
            line += "\n"
        self.sock.sendall(line.encode())

    def send_cmd(self, cmd: str) -> bool:
        if len(self.pending) >= self.max_pending:
            return False
        qdepth = len(self.pending)
        self.send_raw(cmd)
        self.pending.append((cmd, time.time(), qdepth))
        self.log(f"[AI -> SERVER] {cmd}")
        return True

    def log(self, msg: str) -> None:
        # Hot-path logging, gated: silent unless -v. Lifecycle markers
        # (level-ups, death, fork) use print() directly so they always show.
        if self.verbose:
            print(msg, file=sys.stderr)

    def has_pending(self) -> bool:
        return len(self.pending) > 0

    def front_pending(self) -> Optional[str]:
        # The command the next server reply will answer (oldest unanswered).
        return self.pending[0][0] if self.pending else None

    def pop_pending(self) -> Optional[str]:
        # Consume the oldest outstanding command (a reply just arrived for it).
        if not self.pending:
            return None
        cmd, sent_at, qdepth = self.pending.pop(0)
        self.observe_frequency(cmd, sent_at, qdepth)
        return cmd

    def observe_frequency(self, cmd: str, sent_at: float, qdepth: int) -> None:
        # Refine self.frequency from this reply's real latency. Free: no extra
        # commands, no movement -- piggybacks on traffic we already generate.
        if self.frequency_override is not None:
            return
        # After a wedge-drop the FIFO reply<->command mapping is broken: the
        # server's late reply now lands on the wrong pending entry, so its
        # measured latency is garbage (often near zero -> a huge bogus sample
        # that would yank the estimate up and trigger MORE false timeouts).
        # Refuse to sample until the pipeline drains and resyncs.
        if self.pipeline_desynced:
            return
        # Behind a queue -> latency includes earlier commands' execution, so the
        # sample is inflated. Skip; plenty of clean (qdepth==0) samples arrive.
        if qdepth != 0:
            return
        cost = self.cmd_tick_cost.get(cmd, 0)
        if cost <= 0:  # instant or unknown -> no signal
            return
        elapsed = time.time() - sent_at
        if elapsed <= 0:
            return
        sample = cost / elapsed  # ticks per second
        # Discard (don't smooth) implausible samples instead of clamping them in:
        # a clamped extreme still poisons the EMA. The server caps well under 1e4.
        if not (1.0 <= sample <= 10000.0):
            return
        if self.freq_ema is None:
            self.freq_ema = sample
        # A sustained >3x gap means the operator retuned the time unit; crawling
        # there via EMA strands the bot on stale timeouts for dozens of samples.
        # Snap straight to the new sample instead.
        elif sample > 3 * self.freq_ema or sample * 3 < self.freq_ema:
            self.freq_ema = sample
        else:
            self.freq_ema = 0.3 * sample + 0.7 * self.freq_ema
        new_freq = max(1, round(self.freq_ema))
        if new_freq != self.frequency:
            self.frequency = new_freq
            self.max_plan_length = 2 if self.frequency >= 100 else 3

    def read_available(self) -> List[str]:
        if not self.sock:
            return []

        out: List[str] = []

        while True:
            readable, _, _ = select.select([self.sock], [], [], 0)
            if not readable:
                break

            try:
                data = self.sock.recv(4096)
            except BlockingIOError:
                break
            except ConnectionResetError:
                out.append("dead")
                break

            if not data:
                out.append("dead")
                break

            self.recv_buffer += data.decode(errors="ignore")

            while "\n" in self.recv_buffer:
                line, self.recv_buffer = self.recv_buffer.split("\n", 1)
                out.append(line.strip())

        return out

    def read_blocking(self, timeout: float = 5.0) -> str:
        if self.blocking_buffer:
            return self.blocking_buffer.pop(0)

        start = time.time()

        while time.time() - start < timeout:
            lines = self.read_available()
            if lines:
                self.blocking_buffer.extend(lines)
                return self.blocking_buffer.pop(0)
            time.sleep(0.005)

        raise TimeoutError("timeout waiting server")

    def cmd_timeout(self, cmd: str) -> float:
        if cmd in ("Inventory", "Connect_nbr"):
            return max(1.0, 5.0 / self.frequency)
        if cmd == "Fork":
            return max(2.0, 70.0 / self.frequency)
        if cmd == "Incantation":
            return max(5.0, 380.0 / self.frequency)
        return max(1.0, 25.0 / self.frequency)

    def handshake(self) -> None:
        welcome = self.read_blocking()
        if welcome != "WELCOME":
            raise RuntimeError(f"expected WELCOME, got {welcome}")

        self.send_raw(self.team)

        slots = self.read_blocking()
        dims = self.read_blocking()

        try:
            self.memory.free_slots = int(slots)
        except ValueError:
            self.memory.free_slots = 0

        width, height = dims.split()
        self.memory.width = int(width)
        self.memory.height = int(height)

        for line in self.blocking_buffer:
            self.handle_line(line)
        self.blocking_buffer.clear()

        if self.frequency_override is None:
            self.frequency = self.estimate_frequency()
        else:
            self.frequency = self.frequency_override

        self.max_plan_length = 2 if self.frequency >= 100 else 3

        self.log(
            f"[AI] Connected team={self.team} bot_id={self.bot_id} "
            f"slots={self.memory.free_slots} map={self.memory.width}x{self.memory.height} "
            f"freq={self.frequency}",
        )

        self.send_cmd("Inventory")

    def estimate_frequency(self) -> int:
        def round_trip(cmd: str, ok) -> Optional[float]:
            start = time.perf_counter()
            self.send_raw(cmd)

            while time.perf_counter() - start < 60:
                for line in self.read_available():
                    if ok(line):
                        return time.perf_counter() - start
                    self.blocking_buffer.append(line)
                time.sleep(0.0005)

            return None

        connect_times = []
        forward_times = []

        for _ in range(4):
            dt = round_trip("Connect_nbr", lambda lamb: lamb.lstrip("-").isdigit())
            if dt is None:
                return 100
            connect_times.append(dt)

        for _ in range(4):
            dt = round_trip("Forward", lambda lamb: lamb == "ok")
            if dt is None:
                return 100
            forward_times.append(dt)

        delta = min(forward_times) - min(connect_times)
        if delta <= 0:
            delta = min(forward_times)

        return max(1, round(7 / delta))


# ---- protocol.py -------------------------------------------------------

"""ProtocolMixin: protocol responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class ProtocolMixin:
    def parse_inventory(self, line: str) -> Dict[str, int]:
        inv = {r: 0 for r in RESOURCES}
        clean = line.strip()[1:-1]

        for part in clean.split(","):
            toks = part.strip().split()
            if len(toks) == 2 and toks[0] in inv:
                try:
                    inv[toks[0]] = int(toks[1])
                except ValueError:
                    pass

        return inv

    def parse_look(self, line: str) -> List[List[str]]:
        return [tile.strip().split() for tile in line.strip()[1:-1].split(",")]

    def is_inventory_line(self, line: str) -> bool:
        if not (line.startswith("[") and line.endswith("]")):
            return False

        clean = line[1:-1].strip()
        if not clean:
            return False

        for part in clean.split(","):
            toks = part.strip().split()
            if len(toks) != 2 or toks[0] not in RESOURCES or not toks[1].isdigit():
                return False

        return True

    def parse_broadcast(self, line: str) -> Optional[Tuple[int, str]]:
        if not line.startswith("message "):
            return None

        try:
            prefix, text = line.split(",", 1)
            return int(prefix.replace("message", "").strip()), text.strip()
        except ValueError:
            return None

    def parse_team_payload(self, text: str) -> Tuple[str, Dict[str, str]]:
        parts = text.split(":")
        if len(parts) < 2 or parts[0] != self.team:
            return "", {}

        fields = {}

        for part in parts[2:]:
            if "=" in part:
                k, v = part.split("=", 1)
                fields[k] = v

        return parts[1], fields

    def get_int(self, fields: Dict[str, str], key: str) -> Optional[int]:
        try:
            return int(fields[key])
        except (KeyError, ValueError):
            return None


# ---- sensing.py --------------------------------------------------------

"""SensingMixin: sensing responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class SensingMixin:
    def should_refresh_inventory(self) -> bool:
        if self.preparing_incantation:
            return False

        if self.memory.last_inventory_at == 0 or self.memory.inventory_dirty:
            return True

        if time.time() - self.memory.last_inventory_at > max(
            1.0, 120.0 / self.frequency
        ):
            return True

        if self.food() <= 5:
            return self.memory.actions_since_inventory >= 1

        if self.food() <= 10:
            return self.memory.actions_since_inventory >= 2

        return self.memory.actions_since_inventory >= 4

    def needs_look(self) -> bool:
        if self.memory.force_look or not self.memory.visible_tiles:
            return True

        return self.memory.moves_since_look >= (1 if self.food() <= 5 else 2)

    def count_action(self, cmd: str) -> None:
        if cmd and cmd != "Inventory":
            self.memory.actions_since_inventory += 1

        if cmd in ("Forward", "Left", "Right"):
            self.memory.moves_since_look += 1

    def mark_dirty(self, cmd: str) -> None:
        if (
            cmd.startswith("Take ")
            or cmd.startswith("Set ")
            or cmd in ("Fork", "Eject", "Incantation")
        ):
            self.memory.inventory_dirty = True

    def failed_take(self, item: str) -> None:
        if self.memory.visible_tiles:
            try:
                self.memory.visible_tiles[0].remove(item)
            except ValueError:
                pass

        self.plan.clear()
        self.memory.force_look = True
        self.memory.inventory_dirty = False
        self.memory.moves_since_look = 999

    def food(self) -> int:
        return self.memory.inventory.get("food", 0)

    def find_tile(self, item: str) -> Optional[int]:
        for idx, tile in enumerate(self.memory.visible_tiles):
            if item in tile:
                return idx

        return None

    def players_on_tile(self) -> int:
        if not self.memory.visible_tiles:
            return 1

        return self.memory.visible_tiles[0].count("player")

    def visible_useful_resource(self) -> bool:
        return any(
            item == "food" or (item in STONES and self.need_stone(item))
            for tile in self.memory.visible_tiles
            for item in tile
        )

    def best_current_item(self) -> Optional[str]:
        if not self.memory.visible_tiles:
            return None

        tile = self.memory.visible_tiles[0]

        if "food" in tile and self.food() <= 10:
            return "food"

        for stone in STONES:
            if stone in tile and self.need_stone(stone):
                return stone

        if "food" in tile:
            return "food"

        return None

    def best_resource_tile(self) -> Optional[int]:
        best = None
        score = 0

        for idx, tile in enumerate(self.memory.visible_tiles):
            s = 0

            for item in tile:
                if item == "food":
                    s += 10 if self.food() <= 10 else 2
                elif item in STONES and self.need_stone(item):
                    s += 5

            if s > score:
                score = s
                best = idx

        return best

    def best_food_tile(self) -> Optional[int]:
        best = None
        best_score = -999

        for idx, tile in enumerate(self.memory.visible_tiles):
            count = tile.count("food")
            if count <= 0:
                continue

            dist, off = self.tile_pos(idx)
            score = count * 12 - dist * 2 - abs(off)

            if score > best_score:
                best_score = score
                best = idx

        return best


# ---- movement.py -------------------------------------------------------

"""MovementMixin: movement responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class MovementMixin:
    def move_to_tile(
        self, idx: int, full: bool, terminal: Optional[str] = None
    ) -> None:
        plan = self.plan_to_tile(idx)

        if not full:
            plan = plan[: self.max_plan_length]

        if not plan:
            return

        # Fold the action at the destination (e.g. "Take food") into the SAME
        # pipelined burst, so we don't stall on a separate Look+Take round-trip
        # after arriving. We only append it when the whole path fits (full plan);
        # a truncated path doesn't reach the tile yet. If the item moved/was taken
        # meanwhile the Take just ko's — cheap.
        if terminal and full:
            plan.append(terminal)

        first = plan.pop(0)
        self.plan = plan

        self.log(f"[AI] moving toward tile={idx} plan={[first] + plan}")
        self.send_cmd(first)

    def send_next_plan_cmd(self) -> bool:
        # A movement plan is a committed, deterministic sequence, so it is safe to
        # pipeline: push as many steps as the pipeline allows in one tick instead
        # of one per round-trip. The server runs them back-to-back with no idle gap.
        sent = False
        while self.plan and len(self.pending) < self.max_pending:
            cmd = self.plan.pop(0)
            if not self.send_cmd(cmd):
                break
            sent = True
            if not self.plan:
                self.memory.force_look = True
        return sent

    def tile_pos(self, idx: int) -> Tuple[int, int]:
        dist = int(idx**0.5)

        while (dist + 1) * (dist + 1) <= idx:
            dist += 1

        while dist * dist > idx:
            dist -= 1

        start = dist * dist
        center = start + dist

        return dist, idx - center

    def plan_to_tile(self, idx: int) -> List[str]:
        if idx <= 0:
            return []

        dist, off = self.tile_pos(idx)

        if off == 0:
            return ["Forward"] * dist

        if off < 0:
            return ["Left"] + ["Forward"] * abs(off) + ["Right"] + ["Forward"] * dist

        return ["Right"] + ["Forward"] * abs(off) + ["Left"] + ["Forward"] * dist

    def set_follow_plan(self, direction: int) -> None:
        if (
            self.waiting_incantation
            or self.preparing_incantation
            or self.food() <= self.survive_min()
        ):
            return

        # Frozen for a ritual: stay put, don't chase.
        if time.time() < self.arrived_hold_until:
            return

        # Bearing 0 = we're on the leader's tile. Latch a freeze so we hold here
        # for the ritual even after the leader stops broadcasting to run it.
        if direction == 0:
            self.arrived_hold_until = max(
                self.arrived_hold_until, time.time() + self.incant_hold_window()
            )
            return

        if self.plan:
            return

        plan = self.broadcast_plan(direction)[: self.max_plan_length]

        if plan:
            self.log(f"[AI] following broadcast direction={direction} plan={plan}")
            self.plan = plan

    def broadcast_plan(self, direction: int) -> List[str]:
        # K is the server's sound bearing in our own frame: 0 = same tile, 1 =
        # straight ahead, then CLOCKWISE to 8 (server broadcast_direction /
        # test_game_rules). So 3 = our right, 5 = behind, 7 = our left. Step so the
        # source moves toward our front; the leader rebroadcasts and we re-aim.
        if direction == 0:
            return ["Look"]
        if direction in (1, 2, 8):  # ahead or ahead-diagonal -> advance
            return ["Forward"]
        if direction in (3, 4):  # on our right -> face right, advance
            return ["Right", "Forward"]
        if direction == 5:  # directly behind -> turn around
            return ["Right", "Right", "Forward"]
        if direction in (6, 7):  # on our left -> face left, advance
            return ["Left", "Forward"]
        return []


# ---- behaviors.py ------------------------------------------------------

"""BehaviorMixin: behaviors responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class BehaviorMixin:
    def survive(self) -> None:
        if not self.memory.visible_tiles:
            self.send_cmd("Look")
            return

        if self.memory.moves_since_look > 0:
            self.send_cmd("Look")
            return

        tile = self.find_tile("food")

        if tile == 0:
            self.send_cmd("Take food")
        elif tile is not None:
            self.move_to_tile(tile, True, "Take food")
        else:
            self.send_cmd("Forward")

    def collect(self) -> None:
        item = self.best_current_item()

        if item:
            self.send_cmd(f"Take {item}")
            return

        tile = self.best_resource_tile()

        if tile is not None:
            self.move_to_tile(tile, False)
        else:
            self.explore()

    def farm_food(self) -> None:
        if not self.memory.visible_tiles:
            self.send_cmd("Look")
            return

        if "food" in self.memory.visible_tiles[0]:
            self.send_cmd("Take food")
            return

        tile = self.best_food_tile()

        if tile is not None:
            self.move_to_tile(tile, True, "Take food")
        elif self.memory.moves_since_look >= 1:
            self.send_cmd("Look")
        else:
            self.send_cmd("Forward")

    def explore(self) -> None:
        if self.memory.was_ejected:
            self.memory.was_ejected = False
            self.send_cmd("Look")
            return

        if self.is_following():
            self.send_cmd("Look")
            return

        if self.memory.moves_since_look >= 2:
            self.send_cmd("Look")
            return

        r = random.random()

        if r < 0.65:
            self.send_cmd("Forward")
        elif r < 0.825:
            self.send_cmd("Left")
        else:
            self.send_cmd("Right")

    def prepare_incantation(self) -> None:
        if not self.preparing_incantation:
            self.preparing_incantation = True
            self.plan.clear()
            self.clear_following()
            self.stones_to_drop = []

            for stone in STONES:
                self.stones_to_drop += [stone] * REQ[self.memory.level].get(stone, 0)

        if self.stones_to_drop:
            self.send_cmd(f"Set {self.stones_to_drop.pop(0)}")
        else:
            self.send_cmd("Incantation")
            self.waiting_incantation = True

    def reproduce(self) -> None:
        self.clear_following()
        self.abort_gather("reproduce", False)
        self.send_cmd("Fork")

    def after_incantation_done(self) -> None:
        self.preparing_incantation = False
        self.waiting_incantation = False
        self.stones_to_drop.clear()
        self.plan.clear()
        self.clear_following()
        self.memory.inventory_dirty = True
        self.memory.force_look = True

    def spawn_child_for_egg(self) -> None:
        """Launch a fresh AI process to occupy the egg this player just laid.

        Server Fork only creates an egg + frees one team slot; a player hatches
        from it only when a new client connects with the team name. So every
        successful Fork must spawn a new process, else eggs rot and the team
        population can never grow past the initial bots.
        """
        argv = [
            sys.executable,
            os.path.abspath(sys.argv[0]),
            "-p",
            str(self.port),
            "-n",
            self.team,
            "-h",
            self.host,
        ]
        if self.frequency_override is not None:
            argv += ["-f", str(self.frequency_override)]
        try:
            subprocess.Popen(
                argv,
                stdin=subprocess.DEVNULL,
                start_new_session=True,  # detach: our signals/exit don't kill it
                close_fds=True,  # don't leak our socket into the child
            )
            print(
                f"[AI] spawned child to claim egg ({' '.join(argv)})", file=sys.stderr
            )
        except OSError as error:
            print(f"[AI] failed to spawn child for egg: {error}", file=sys.stderr)

    def survive_min(self) -> int:
        # Level-scaled survival floor: bail to eat well before starving, more so
        # the higher (more valuable) the bot is.
        return self.survive_food + (self.memory.level - 1) * self.survive_per_level

    def gather_abort_min(self) -> int:
        # Abort a gather to forage a couple food above the pure-survival floor,
        # so coordinating never tips a high-level bot into starvation.
        return self.survive_min() + 2

    def gather_start_min(self) -> int:
        # Only START a gather with a healthy cushion above the survival floor.
        # (+16 over the flat floor of 8 = 24, the original tuned value.)
        return self.survive_min() + 16

    def has_required_stones(self) -> bool:
        requirements = REQ.get(self.memory.level)
        if not requirements:
            return False

        for stone in STONES:
            if self.memory.inventory.get(stone, 0) < requirements.get(stone, 0):
                return False

        self.log(f"[AI] has stones for lvl {self.memory.level}, ready to incant")
        return True

    def need_stone(self, stone: str) -> bool:
        if not self.manifest_gave_up:
            return self.memory.inventory.get(stone, 0) < self.manifest_target(stone)
        return self.memory.inventory.get(stone, 0) < REQ.get(self.memory.level, {}).get(
            stone, 0
        )


# ---- gather.py ---------------------------------------------------------

"""GatherMixin: gather responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class GatherMixin:
    def gather_ack_window(self) -> float:
        return max(2.0, 80.0 / self.frequency)

    def gather_rebroadcast_interval(self) -> float:
        return max(0.6, 35.0 / self.frequency)

    def gather_arrival_timeout(self) -> float:
        return max(8.0, 300.0 / self.frequency)

    def incant_hold_window(self) -> float:
        # Seconds a teammate freezes after a HOLD, covering the leader's
        # Set+Incantation cycles so the on-tile player count holds.
        return max(3.0, 150.0 / self.frequency)

    def gather_cooldown(self) -> float:
        return max(4.0, 180.0 / self.frequency)

    def in_gather_cooldown(self) -> bool:
        return (
            self.last_gather_giveup_at > 0
            and time.time() - self.last_gather_giveup_at < self.gather_cooldown()
        )

    def confirmed_players(self) -> int:
        return 1 + len(self.active_acks) if self.active_req else 1

    def locked_leader(self) -> bool:
        return bool(
            self.active_req
            and self.active_need > 0
            and self.confirmed_players() >= self.active_need
        )

    def start_gather(self, need: int) -> None:
        self.gather_counter += 1
        self.gather_attempts += 1
        self.active_req = f"{self.bot_id}-{self.memory.level}-{self.gather_counter}"
        self.active_level = self.memory.level
        self.active_need = need
        self.active_acks.clear()
        self.arrived_at_leader.clear()
        self.gather_started_at = time.time()
        self.gather_last_broadcast_at = 0
        self.gather_arrival_started_at = 0
        self.clear_following()

        self.log(
            f"[AI] new gather req={self.active_req} need={need} attempt={self.gather_attempts}",
        )

        self.broadcast_gather()

    def broadcast_gather(self) -> bool:
        if not self.active_req:
            return False

        msg = (
            f"{self.team}:GATHER:"
            f"req={self.active_req}:"
            f"level={self.active_level}:"
            f"need={self.active_need}:"
            f"from={self.bot_id}"
        )

        if self.send_cmd(f"Broadcast {msg}"):
            self.gather_last_broadcast_at = time.time()
            return True

        return False

    def broadcast_hold(self) -> bool:
        # "Everyone of my level on my tile: freeze, I'm about to incant."
        msg = f"{self.team}:HOLD:level={self.memory.level}:from={self.bot_id}"
        return self.send_cmd(f"Broadcast {msg}")

    def abort_gather(self, reason: str, giveup: bool) -> None:
        if not self.active_req:
            return

        self.log(f"[AI] abort gather req={self.active_req}: {reason}")

        self.active_req = None
        self.active_level = 0
        self.active_need = 0
        self.active_acks.clear()
        self.gather_started_at = 0
        self.gather_last_broadcast_at = 0
        self.gather_attempts = 0
        self.gather_arrival_started_at = 0

        if giveup:
            self.last_gather_giveup_at = time.time()
            self.clear_following()

            if self.need_more_mates():
                self.must_fork_after_gather_fail = True
                self.log("[AI] gather failed -> switch objective to FARM_FOOD/FORK")

    def call_teammates(self) -> None:
        now = time.time()
        need = REQ[self.memory.level]["players"]
        # Manifest anchor wants a full 6-stack so one drop+blitz rides L2->L8.
        manifest_anchor = self.has_full_manifest()
        if manifest_anchor:
            need = 6

        # The manifest anchor holds the rally on its banked reserve — it must NOT
        # bail at gather_abort_min (that was the 813-abort thrash). It rides down to
        # survive_min (choose_state's survival preempt), eating any tile food first.
        if self.food() <= self.gather_abort_min() and not manifest_anchor:
            self.abort_gather("food too low while waiting teammates", True)
            self.state = State.SURVIVE
            self.survive()
            return

        if self.memory.visible_tiles and "food" in self.memory.visible_tiles[0]:
            self.send_cmd("Take food")
            return

        # Count only same-level teammates that announced ARRIVED (physically on my
        # tile, server-verified via bearing 0) — NOT players_on_tile(), which is
        # level-blind and fires on passing level-1 babies -> guaranteed ko.
        present = 1 + len(self.arrived_at_leader)

        if present < need:
            self.incant_hold_broadcasts = 0

        if present >= need:
            # Freeze teammates BEFORE the multi-step ritual, else they wander off
            # mid-Set/Incantation and the count drops below need -> ko. Broadcast
            # HOLD a couple times so everyone latches a freeze, then incant.
            if self.incant_hold_broadcasts < 2:
                if self.broadcast_hold():
                    self.incant_hold_broadcasts += 1
                return
            self.incant_hold_broadcasts = 0
            self.abort_gather("enough ARRIVED on tile", False)
            if manifest_anchor:
                self.start_manifest_blitz()
            else:
                self.prepare_incantation()
            return

        if not self.active_req:
            self.gather_attempts = 0
            self.start_gather(need)
            return

        if manifest_anchor:
            # Persistent rally: convergence is tracked by ARRIVED (physical, set in
            # handle_arrived), which only accumulates if we DON'T reset the gather.
            # So NEVER restart/abort on ACK count here (that wiped the count, the
            # 997-abort thrash). Just keep the bearing alive and wait for bodies.
            if now - self.gather_last_broadcast_at > self.gather_rebroadcast_interval():
                self.broadcast_gather()
                return
            if now - self.gather_started_at > max(90.0, 90000.0 / self.frequency):
                self.abort_gather("manifest rally timed out", True)
                self.manifest_gave_up = True
                self.state = State.EXPLORE
                return
            self.send_cmd("Look")
            return

        confirmed = self.confirmed_players()

        if confirmed >= need:
            if self.gather_arrival_started_at <= 0:
                self.gather_arrival_started_at = now
                self.log(
                    f"[AI] enough ACK for req={self.active_req} confirmed={confirmed}/{need}; "
                    f"locked leader, waiting on tile",
                )

            if now - self.gather_last_broadcast_at > self.gather_rebroadcast_interval():
                self.broadcast_gather()
                return

            # The manifest anchor must assemble 6 scattered collectors — give it
            # far more patience than a normal 2-player gather, and keep waiting
            # (eating on tile) rather than scattering to farm/fork.
            arrival_timeout = self.gather_arrival_timeout() * (
                8 if manifest_anchor else 1
            )
            if now - self.gather_arrival_started_at > arrival_timeout:
                self.abort_gather("mates did not arrive on tile", True)
                self.state = State.REPRODUCE if self.should_fork() else State.FARM_FOOD
                self.run_state()
                return

            self.send_cmd("Look")
            return

        if now - self.gather_started_at >= self.gather_ack_window():
            if self.gather_attempts < 3:
                self.start_gather(need)
                return

            self.abort_gather(f"not enough ACK ({confirmed}/{need})", True)
            self.state = State.REPRODUCE if self.should_fork() else State.FARM_FOOD
            self.run_state()
            return

        if now - self.gather_last_broadcast_at > self.gather_rebroadcast_interval():
            self.broadcast_gather()
            return

        self.send_cmd("Look")

    def handle_gather(
        self, direction: int, fields: Dict[str, str], sender: int
    ) -> None:
        req_id = fields.get("req", "")
        level = self.get_int(fields, "level")

        if not req_id or level is None:
            return

        self.memory.last_gather_at = time.time()

        if self.locked_leader():
            self.log(
                f"[AI] locked gather leader req={self.active_req} "
                f"confirmed={self.confirmed_players()}/{self.active_need}; "
                f"ignore gather from={sender}",
            )
            return

        if (
            self.is_following()
            and self.following_leader is not None
            and sender > self.following_leader
        ):
            return

        if self.active_req:
            if sender < self.bot_id:
                self.abort_gather(
                    f"lower bot_id leader wins before lock: {sender} < {self.bot_id}",
                    False,
                )
            else:
                return

        if not self.can_answer_gather(level, sender):
            return

        self.following_req = req_id
        self.following_leader = sender
        self.following_until = time.time() + self.gather_arrival_timeout()
        self.queue_ack(req_id, level, sender)
        self.pending_follow_direction = direction

        # Bearing 0 from our leader = we are physically on its exact tile. Announce
        # ARRIVED so it can count us as a confirmed same-level body. Re-announced on
        # every direction-0 rebroadcast (self-throttled), so a lost one self-heals.
        if direction == 0:
            self.send_cmd(
                f"Broadcast {self.team}:ARRIVED:req={req_id}:level={level}:from={self.bot_id}"
            )

    def handle_ack(self, fields: Dict[str, str], sender: int) -> None:
        req_id = fields.get("req", "")
        level = self.get_int(fields, "level")

        if self.active_req and req_id == self.active_req and level == self.memory.level:
            if sender not in self.active_acks:
                self.log(
                    f"[AI] GATHER_ACK req={req_id} from={sender} "
                    f"confirmed={1 + len(self.active_acks) + 1}/{self.active_need}",
                )

            self.active_acks[sender] = time.time()

    def handle_arrived(self, fields: Dict[str, str], sender: int) -> None:
        # A same-level teammate reports it's physically on my gather tile.
        req_id = fields.get("req", "")
        level = self.get_int(fields, "level")
        if self.active_req and req_id == self.active_req and level == self.memory.level:
            if sender not in self.arrived_at_leader:
                self.log(
                    f"[AI] ARRIVED req={req_id} from={sender} "
                    f"present={1 + len(self.arrived_at_leader) + 1}/{self.active_need}",
                )
            self.arrived_at_leader.add(sender)

    def handle_hold(self, fields: Dict[str, str], sender: int) -> None:
        level = self.get_int(fields, "level")
        if level != self.memory.level:
            return
        if self.preparing_incantation or self.waiting_incantation:
            return
        if self.food() <= self.survive_min():
            return  # too hungry to wait; survival wins
        # Only freeze if we're actually converging on THIS leader — otherwise a
        # map-wide broadcast would freeze distant non-participants and starve them.
        if not (self.is_following() and self.following_leader == sender):
            return
        self.arrived_hold_until = time.time() + self.incant_hold_window()

    def can_answer_gather(self, level: int, leader: int) -> bool:
        return (
            leader != self.bot_id
            and level == self.memory.level
            and not self.preparing_incantation
            and not self.waiting_incantation
            and self.food() > self.survive_min()
        )

    def queue_ack(self, req_id: str, level: int, leader: int) -> None:
        if req_id in self.answered_reqs or self.pending_ack_req == req_id:
            return

        self.pending_ack_req = req_id
        self.pending_ack_level = level
        self.pending_ack_leader = leader

        self.log(f"[AI] queued GATHER_ACK req={req_id} leader={leader}")

    def send_pending_ack(self) -> bool:
        if not self.pending_ack_req:
            return False

        if (
            self.food() <= self.survive_min()
            or self.preparing_incantation
            or self.waiting_incantation
        ):
            self.pending_ack_req = None
            return False

        msg = (
            f"{self.team}:GATHER_ACK:"
            f"req={self.pending_ack_req}:"
            f"level={self.pending_ack_level}:"
            f"from={self.bot_id}"
        )

        if not self.send_cmd(f"Broadcast {msg}"):
            return False

        self.answered_reqs[self.pending_ack_req] = time.time()
        self.pending_ack_req = None
        self.pending_ack_level = 0
        self.pending_ack_leader = None
        return True

    def prune_answered_reqs(self) -> None:
        now = time.time()
        ttl = max(30.0, 1000.0 / self.frequency)
        self.answered_reqs = {
            req: t for req, t in self.answered_reqs.items() if now - t <= ttl
        }

    def clear_following(self) -> None:
        self.following_req = None
        self.following_leader = None
        self.following_until = 0
        self.pending_follow_direction = None

    def is_following(self) -> bool:
        if not self.following_req:
            return False

        if time.time() > self.following_until:
            self.clear_following()
            return False

        return True


# ---- manifest.py -------------------------------------------------------

"""ManifestMixin: manifest responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class ManifestMixin:
    def broadcast_focus_food(self) -> None:
        self.last_focus_bcast = time.time()
        self.send_cmd(
            f"Broadcast {self.team}:MFOOD:level={self.memory.level}:from={self.bot_id}"
        )

    def broadcast_ready(self) -> None:
        self.last_ready_bcast = time.time()
        self.send_cmd(
            f"Broadcast {self.team}:MRDY:level={self.memory.level}:from={self.bot_id}"
        )

    def broadcast_ready_too(self) -> None:
        self.last_ready_bcast = time.time()
        self.send_cmd(
            f"Broadcast {self.team}:MRDY2:level={self.memory.level}:from={self.bot_id}"
        )

    def broadcast_come_now(self) -> None:
        self.send_cmd(
            f"Broadcast {self.team}:MCOME:level={self.memory.level}:from={self.bot_id}"
        )

    def manifest_demote_to(self, anchor_id: int) -> None:
        # A lower-id anchor exists -> stop being an anchor, rally to it instead.
        self.manifest_is_anchor = False
        self.manifest_anchor = anchor_id
        self.ready_too.clear()
        self.abort_gather("defer to lower-id manifest anchor", False)
        if self.manifest_phase in ("collect", "bank", "ready", "converge"):
            if self.manifest_phase == "collect":
                self.manifest_phase = "bank"

    def handle_mfood(self, fields: Dict[str, str], sender: int) -> None:
        if self.get_int(fields, "level") != self.memory.level:
            return
        if self.manifest_is_anchor:
            if sender < self.bot_id:
                self.manifest_demote_to(sender)
            return
        # Member: stop collecting, rally to this anchor, start banking food.
        self.manifest_anchor = sender
        if self.manifest_phase == "collect":
            self.manifest_phase = "bank"

    def handle_mrdy(self, fields: Dict[str, str], sender: int) -> None:
        # Anchor announcing it's fed + ready (also gives us its bearing).
        if self.get_int(fields, "level") != self.memory.level:
            return
        if self.manifest_is_anchor:
            if sender < self.bot_id:
                self.manifest_demote_to(sender)
            return
        self.manifest_anchor = sender

    def handle_mrdy2(self, fields: Dict[str, str], sender: int) -> None:
        # A member reports it's fed + ready.
        if (
            self.manifest_is_anchor
            and self.get_int(fields, "level") == self.memory.level
        ):
            self.ready_too.add(sender)

    def handle_mcome(self, fields: Dict[str, str], sender: int) -> None:
        # Launch: converge on the anchor (its GATHER drives the actual follow).
        if self.manifest_is_anchor:
            return
        if self.get_int(fields, "level") != self.memory.level:
            return
        self.manifest_anchor = sender
        self.manifest_phase = "converge"

    def manifest_target(self, stone: str) -> int:
        # Total of this stone needed to ritual from our current level all the way
        # to L8 (one ritual per level; each elevates all 6 players).
        return sum(REQ[lvl].get(stone, 0) for lvl in range(self.memory.level, 8))

    def has_full_manifest(self) -> bool:
        return all(
            self.memory.inventory.get(s, 0) >= self.manifest_target(s) for s in STONES
        )

    def manifest_drop_list(self) -> List[str]:
        out: List[str] = []
        for s in STONES:
            out += [s] * self.manifest_target(s)
        return out

    def manifest_visible(self) -> bool:
        return any(
            item in STONES and self.need_stone(item)
            for tile in self.memory.visible_tiles
            for item in tile
        )

    def manifest_timeout(self) -> float:
        # If no anchor emerges (e.g. no thystame on the map) within this, give up
        # the strategy and play normally so the team isn't stuck forever.
        return max(300.0, 200000.0 / self.frequency)

    def manifest_choose(self) -> None:
        # Phased rendezvous. choose_state already handled survival/HOLD/preparing.
        now = time.time()
        phase = self.manifest_phase

        # ---- COLLECT: race to complete the full L2->L8 stone set -------------
        if phase == "collect":
            if self.has_full_manifest():
                # First to complete becomes the anchor: tell the team to stop
                # collecting and bank food, then bank ourselves.
                self.manifest_is_anchor = True
                self.manifest_phase = "bank"
                self.broadcast_focus_food()
                self.state = State.FARM_FOOD
                return
            # keep a fat food buffer while collecting (collection is cheap)
            if self.food() < self.manifest_food_floor:
                self.state = State.FARM_FOOD
                return
            if time.time() - self.manifest_started_at > self.manifest_timeout():
                self.manifest_gave_up = True  # no anchor ever emerged -> normal play
                self.state = State.EXPLORE
                return
            self.state = State.COLLECT if self.manifest_visible() else State.EXPLORE
            return

        # ---- BANK: everyone fills food to a reserve before converging --------
        if phase == "bank":
            if self.food() < self.food_reserve:
                self.state = State.FARM_FOOD
                return
            self.manifest_phase = "ready"  # banked -> signal readiness
            self.state = State.LOOK
            return

        # ---- READY: fed and waiting; anchor synchronises the launch ----------
        if phase == "ready":
            if self.manifest_is_anchor:
                # Re-bank if our reserve ran down while waiting for stragglers.
                if self.food() < self.food_abort:
                    self.manifest_phase = "bank"
                    self.ready_too.clear()
                    self.state = State.FARM_FOOD
                    return
                # Count only members still heartbeating (census liveness): a
                # READY_TOO from a bot that has since starved must not let the
                # launch fire with 5 bodies.
                if len(self.ready_too & self.team_members) + 1 >= 6:
                    # All 6 fed and ready -> launch: COME_NOW + open the gather.
                    self.broadcast_come_now()
                    self.manifest_phase = "converge"
                    self.start_gather(6)
                    self.state = State.CALL_TEAMMATES
                    return
                # Keep broadcasting READY (gives members our bearing) + eat in
                # place: FARM_FOOD only Takes food already under us (no move) when
                # the tile has it, so we stay put as the rendezvous beacon.
                if now - self.last_ready_bcast > self.gather_rebroadcast_interval():
                    self.broadcast_ready()
                tile0 = (
                    self.memory.visible_tiles[0] if self.memory.visible_tiles else []
                )
                self.state = State.FARM_FOOD if "food" in tile0 else State.LOOK
                return
            # Member: announce READY_TOO, then hold fed until COME_NOW arrives.
            if now - self.last_ready_bcast > self.gather_rebroadcast_interval():
                self.broadcast_ready_too()
            if self.food() < self.manifest_food_floor:
                self.state = State.FARM_FOOD
                return
            self.state = State.LOOK
            return

        # ---- CONVERGE: full tanks, walk to the anchor, then blitz ------------
        # Anchor drives the gather (ARRIVED count -> drop+blitz). Members follow
        # the anchor's gather bearing (full food survives the trek).
        if self.manifest_is_anchor:
            if not self.active_req:
                self.start_gather(6)
            self.state = State.CALL_TEAMMATES
            return
        if self.is_following():
            self.state = State.LOOK
            return
        # member told to come but no bearing yet (anchor not heard) -> wait fed
        if self.food() < 12:
            self.state = State.FARM_FOOD
            return
        self.state = State.LOOK

    def start_manifest_blitz(self) -> None:
        # Anchor has 6 mates on its tile: drop the whole stone pile, then incant
        # straight up. The Set sequence runs via PREPARE_INCANTATION; on each
        # level-up the Current-level handler fires the next Incantation (stones for
        # the next level are already on the tile).
        self.abort_gather("manifest blitz", False)
        self.preparing_incantation = True
        self.blitzing = True
        self.stones_to_drop = self.manifest_drop_list()


# ---- census.py ---------------------------------------------------------

"""CensusMixin: census responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class CensusMixin:
    def hello_interval(self) -> float:
        return max(1.0, 60.0 / self.frequency)

    def member_ttl(self) -> float:
        # Silence longer than this means the member is dead (death sends no
        # broadcast, so absence of heartbeats is the only signal). Must exceed
        # the longest legitimate silence: an Incantation freezes a bot for
        # 300/f s, and the quorum-met heartbeat runs at 2x hello_interval.
        return max(6.0 * self.hello_interval(), 320.0 / self.frequency, 10.0)

    def census_window(self) -> float:
        # Window scaled to game speed: each fork needs a 42/f-t.u. hatch plus
        # client boot plus food farming, so a fixed wall-clock 30s starves the
        # census at low f. 3000/f == the env default 30s at f=100.
        return max(self.census_timeout, 3000.0 / self.frequency)

    def broadcast_hello(self) -> None:
        self.last_hello_at = time.time()
        self.send_cmd(f"Broadcast {self.team}:HELLO:from={self.bot_id}")

    def handle_hello(self, sender: int) -> None:
        known = sender in self.team_members
        self.team_members.add(sender)
        self.team_last_seen[sender] = time.time()
        if known:
            return  # heartbeat from a known member: last_seen refreshed above
        # A new body showed up -> the fork we were waiting on (or a sibling)
        # landed; release the in-flight hold so the forker can continue.
        self.census_fork_deadline = 0.0
        self.log(
            f"[AI] census +{sender} -> {len(self.team_members)}/{self.census_target}"
        )
        # Echo once so the newcomer learns about us too. Bounded: only on the
        # first sighting of a given id, never on repeat HELLOs.
        self.broadcast_hello()

    def evict_silent_members(self) -> None:
        # Prune presumed-dead members. This is what re-breaks the quorum after
        # a death (so the census re-arms) and re-elects the forker when the
        # corpse held the lowest id.
        cutoff = time.time() - self.member_ttl()
        for mid in [m for m in self.team_members if m != self.bot_id]:
            if self.team_last_seen.get(mid, 0.0) < cutoff:
                self.team_members.discard(mid)
                self.team_last_seen.pop(mid, None)
                self.log(
                    f"[AI] census -{mid} (silent) -> "
                    f"{len(self.team_members)}/{self.census_target}"
                )

    def census_active(self) -> bool:
        if self.manifest_gave_up or self.census_deadline is None:
            return False
        if len(self.team_members) >= self.census_target:
            return False
        return time.time() < self.census_deadline

    def is_census_forker(self) -> bool:
        # Lowest known id is elected. Recomputed each call, so a lower id that
        # appears late takes over automatically.
        return self.bot_id == min(self.team_members)

    def census_maintain(self) -> None:
        now = time.time()
        if self.census_deadline is None:  # first tick: start clocks
            self.census_deadline = now + self.census_window()
            self.census_settle_until = now + self.census_settle
            self.broadcast_hello()
            return
        if self.manifest_gave_up:
            return  # fallback play: no quorum bookkeeping

        self.evict_silent_members()

        # Heartbeat forever, not just during the opening window: continuous
        # liveness is what lets survivors detect a death and re-fork back to
        # quorum. Halved rate once the quorum is met (pure liveness traffic).
        interval = self.hello_interval()
        if len(self.team_members) >= self.census_target:
            interval *= 2.0
        if now - self.last_hello_at >= interval:
            self.broadcast_hello()

        # Quorum broken with the window closed (a member died, or the opening
        # window was too short to finish forking): re-open it so the elected
        # forker repopulates. Short settle: one heartbeat round, enough to
        # hear a member the eviction wrongly presumed dead.
        if len(self.team_members) < self.census_target and now >= self.census_deadline:
            self.census_deadline = now + self.census_window()
            self.census_settle_until = now + self.hello_interval()
            self.log(
                f"[AI] census re-armed: {len(self.team_members)}/{self.census_target}"
            )

    def should_fork(self) -> bool:
        if (
            self.active_req
            or self.is_following()
            or self.preparing_incantation
            or self.waiting_incantation
        ):
            return False

        if self.food() < self.fork_food:
            return False

        if time.time() - self.memory.last_fork_at < max(3.0, 150.0 / self.frequency):
            return False

        # Fallback (no quorum ever formed): original per-bot cap behaviour.
        # Only low-level bots reproduce here — the cap exists to limit mouths
        # on a scarce map, not to restore a quorum, and a level-3+ bot is too
        # valuable and food-bound to pay ~6 food for a level-1 baby.
        if self.manifest_gave_up:
            if self.memory.level > 2:
                return False
            return self.memory.forks_done < self.max_forks

        # Census mode: the team is sized to the blitz quorum, not a per-bot cap.
        # No level gate here: after deaths the survivors may all be level 3+,
        # and the elected forker forking is the only path back to quorum —
        # gating it stalls the blitz forever at 5 bots.
        if len(self.team_members) >= self.census_target:
            return False  # quorum met -> nobody forks
        if not self.census_active():
            return False  # window closed; census_maintain re-arms it next tick
        if self.census_settle_until and time.time() < self.census_settle_until:
            return False  # let initial HELLOs land first
        if time.time() < self.census_fork_deadline:
            return False  # a forked child hasn't announced yet
        return self.is_census_forker()

    def need_more_mates(self) -> bool:
        return (
            REQ.get(self.memory.level, {}).get("players", 1) > 1
            and self.has_required_stones()
        )


# ---- brain.py ----------------------------------------------------------

"""BrainMixin: brain responsibilities of the AI.

Auto-split from the original monolith; bodies are byte-identical.
The build bundler (_bundle.py) re-stitches these into a single zappy_ai."""



class BrainMixin:
    def run(self) -> int:
        # Auto-reap forked children so spawned bots don't pile up as zombies.
        if hasattr(signal, "SIGCHLD"):
            signal.signal(signal.SIGCHLD, signal.SIG_IGN)

        self.connect()
        self.handshake()

        while self.running:
            # Block until the socket has data instead of busy-polling on a fixed
            # 2ms sleep. A server reply wakes us instantly (sub-ms), so the
            # reactive feed cycle (Look -> Take) no longer eats a 2ms latency tax
            # per command — that tax is what capped survival at high frequency.
            # The 50ms cap is just a floor so time-based logic (rebroadcast
            # intervals, fork cooldowns, gather timers) still ticks when idle.
            if self.sock is not None:
                try:
                    select.select([self.sock], [], [], 0.05)
                except (OSError, ValueError):
                    pass

            for line in self.read_available():
                if line:
                    self.handle_line(line)

            self.tick()

        if self.sock:
            self.sock.close()

        return 0

    def tick(self) -> None:
        if not self.running or self.state == State.DEAD:
            return

        # Drop a wedged front command (no reply within its timeout) so the
        # pipeline can't stall forever on a lost response.
        if self.pending:
            cmd, at, _ = self.pending[0]
            if time.time() - at > self.cmd_timeout(cmd):
                self.log(f"[AI] command timeout: {cmd}")
                self.pending.pop(0)
                # The lost reply may still arrive and shift onto the wrong entry;
                # stop trusting latency samples until the queue resyncs (empties).
                self.pipeline_desynced = True
        elif self.pipeline_desynced:
            # Queue drained with no outstanding commands -> FIFO is back in sync.
            self.pipeline_desynced = False

        # Opening team census: announce presence so everyone can size the team.
        self.census_maintain()

        # Keep the pipeline topped up with committed plan steps. Safe even while
        # other replies are outstanding — it's a deterministic path, not a
        # state-dependent decision.
        if self.send_next_plan_cmd():
            return

        # Everything below is a reactive decision that must see fresh world state,
        # so only act once the pipeline has drained (preserves single-pending
        # semantics for Look/Inventory/Take/Incantation/etc.).
        if self.has_pending():
            return

        self.prune_answered_reqs()

        if self.send_pending_ack():
            return

        if self.memory.force_look:
            self.memory.force_look = False
            self.send_cmd("Look")
            return

        if self.pending_follow_direction is not None:
            direction = self.pending_follow_direction
            self.pending_follow_direction = None
            self.set_follow_plan(direction)

            if self.send_next_plan_cmd():
                return

        if self.should_refresh_inventory():
            self.send_cmd("Inventory")
            return

        self.choose_state()
        self.run_state()

    def handle_line(self, line: str) -> None:
        self.log(f"[SERVER -> AI] {line}")

        if line == "dead":
            print("[AI] DEAD", file=sys.stderr)  # always: survival metric
            self.state = State.DEAD
            self.running = False
            return

        msg = self.parse_broadcast(line)
        if msg:
            direction, text = msg
            self.handle_team_message(direction, text)
            return

        if line.startswith("eject:"):
            self.memory.was_ejected = True
            self.plan.clear()
            self.memory.force_look = True
            return

        if line.startswith("Current level:"):
            try:
                self.memory.level = int(line.replace("Current level:", "").strip())
            except ValueError:
                pass

            print(
                f"[AI] LEVELUP {self.memory.level}", file=sys.stderr
            )  # always: metric
            self.pop_pending()

            # Manifest blitz: the stones for the NEXT level are already on the tile
            # and the 6 frozen players are still here -> fire the next Incantation
            # immediately, no Set, no re-gather. Ride straight to L8.
            if self.blitzing and self.memory.level < 8:
                self.broadcast_hold()  # keep the frozen mates frozen
                self.send_cmd("Incantation")
                self.waiting_incantation = True
                return

            was_frozen = time.time() < self.arrived_hold_until
            self.blitzing = False
            self.after_incantation_done()
            self.must_fork_after_gather_fail = False
            self.abort_gather("level changed", False)
            self.clear_following()
            # A frozen participant in someone's blitz: keep holding so we stay on
            # the tile for the next ritual instead of wandering after leveling.
            if was_frozen:
                self.arrived_hold_until = time.time() + self.incant_hold_window()
            return

        if line == "Elevation underway":
            return

        if line.lstrip("-").isdigit() and self.front_pending() == "Connect_nbr":
            self.memory.free_slots = int(line)
            self.pop_pending()
            return

        if line in ("ok", "ko"):
            cmd = self.pop_pending() or ""
            self.count_action(cmd)

            if line == "ok":
                self.mark_dirty(cmd)

            if cmd == "Fork" and line == "ok":
                self.memory.forks_done += 1
                self.memory.last_fork_at = time.time()
                self.must_fork_after_gather_fail = False
                # Hold the next census fork until this child announces (HELLO
                # clears it), or until the deadline if it never boots.
                if self.census_active():
                    self.census_fork_deadline = time.time() + self.census_child_timeout
                # Egg laid: launch the client that will hatch from it.
                self.spawn_child_for_egg()
                print(
                    f"[AI] fork ok -> egg laid, spawned client "
                    f"(forks_done={self.memory.forks_done})",
                    file=sys.stderr,
                )

            if cmd == "Incantation":
                # A failed ritual (e.g. a blitz mate left) ends the blitz; the
                # bot drops back to normal manifest decisions next tick.
                self.blitzing = False
                self.after_incantation_done()

            if line == "ko":
                if cmd.startswith("Take "):
                    self.failed_take(cmd.replace("Take ", "", 1))
                    return

                self.memory.inventory_dirty = True
                self.memory.force_look = True

            return

        if line.startswith("[") and line.endswith("]"):
            if self.is_inventory_line(line):
                self.memory.inventory = self.parse_inventory(line)
                self.memory.inventory_dirty = False
                self.memory.last_inventory_at = time.time()
                self.memory.actions_since_inventory = 0
                self.pop_pending()

                self.log(
                    "[AI] inventory updated: "
                    + " ".join(
                        f"{r}={self.memory.inventory.get(r, 0)}" for r in RESOURCES
                    )
                )
            else:
                self.memory.visible_tiles = self.parse_look(line)
                self.memory.last_look_at = time.time()
                self.memory.moves_since_look = 0
                self.memory.force_look = False
                self.pop_pending()

            return

        self.log(f"[AI] ignored: {line}")

    def handle_team_message(self, direction: int, text: str) -> None:
        if not text.startswith(f"{self.team}:"):
            return

        kind, fields = self.parse_team_payload(text)
        sender = self.get_int(fields, "from")

        if sender is None or sender == self.bot_id:
            return

        if kind == "HELLO":
            self.handle_hello(sender)
        elif kind == "GATHER":
            self.handle_gather(direction, fields, sender)
        elif kind == "GATHER_ACK":
            self.handle_ack(fields, sender)
        elif kind == "HOLD":
            self.handle_hold(fields, sender)
        elif kind == "ARRIVED":
            self.handle_arrived(fields, sender)
        elif kind == "MFOOD":
            self.handle_mfood(fields, sender)
        elif kind == "MRDY":
            self.handle_mrdy(fields, sender)
        elif kind == "MRDY2":
            self.handle_mrdy2(fields, sender)
        elif kind == "MCOME":
            self.handle_mcome(fields, sender)

    def choose_state(self) -> None:
        food = self.food()

        if food <= self.survive_min():
            self.abort_gather("low food", False)
            self.clear_following()
            self.state = State.SURVIVE
            return

        # Frozen for a teammate's incantation ritual (HOLD): hold position. Survival
        # above still overrides, so we never freeze into starvation.
        if time.time() < self.arrived_hold_until and not self.preparing_incantation:
            self.plan.clear()
            self.state = State.LOOK  # LOOK doesn't move us; we just wait on-tile
            return

        if self.preparing_incantation:
            self.state = (
                State.PREPARE_INCANTATION if self.stones_to_drop else State.INCANT
            )
            return

        if self.needs_look():
            self.state = State.LOOK
            return

        # Opening census: the elected forker builds the team to the blitz quorum
        # before anyone settles into the manifest collect (which never forks).
        # Bounded to the census window, so it stops the moment quorum is met.
        if self.census_active() and self.should_fork():
            self.state = State.REPRODUCE
            return

        # The blitz kicks in at L2: do the quick solo L1->L2 normally first, then
        # collect the L2->L8 manifest and blitz.
        if not self.manifest_gave_up and self.memory.level >= 2:
            self.manifest_choose()
            return

        if self.has_required_stones():
            players = REQ[self.memory.level]["players"]

            if players <= 1:
                self.state = State.PREPARE_INCANTATION
                return

            if self.active_req:
                self.state = State.CALL_TEAMMATES
                return

            if self.is_following():
                self.state = State.LOOK
                return

            if self.must_fork_after_gather_fail:
                self.state = State.REPRODUCE if self.should_fork() else State.FARM_FOOD
                return

            if self.in_gather_cooldown():
                self.state = State.REPRODUCE if self.should_fork() else State.FARM_FOOD
                return

            if food < self.gather_start_min():
                self.state = State.REPRODUCE if self.should_fork() else State.FARM_FOOD
                return

            self.state = State.CALL_TEAMMATES
            return

        self.abort_gather("stones not ready", False)
        self.clear_following()

        if self.should_fork():
            self.state = State.REPRODUCE
        elif self.visible_useful_resource():
            self.state = State.COLLECT
        else:
            self.state = State.EXPLORE

    def run_state(self) -> None:
        self.log(
            f"[AI] state={self.state.value} level={self.memory.level} food={self.food()} "
            f"actions_since_inventory={self.memory.actions_since_inventory} "
            f"moves_since_look={self.memory.moves_since_look}"
        )

        if self.state == State.SURVIVE:
            self.survive()
        elif self.state == State.LOOK:
            self.send_cmd("Look")
        elif self.state == State.COLLECT:
            self.collect()
        elif self.state == State.EXPLORE:
            self.explore()
        elif self.state == State.FARM_FOOD:
            self.farm_food()
        elif self.state == State.CALL_TEAMMATES:
            self.call_teammates()
        elif self.state == State.PREPARE_INCANTATION:
            self.prepare_incantation()
        elif self.state == State.INCANT:
            self.send_cmd("Incantation")
            self.waiting_incantation = True
        elif self.state == State.REPRODUCE:
            self.reproduce()


# ---- ai.py -------------------------------------------------------------

"""The AI class: assembles all mixins and holds construction (__init__)."""




class AI(
    NetMixin,
    ProtocolMixin,
    SensingMixin,
    MovementMixin,
    BehaviorMixin,
    GatherMixin,
    ManifestMixin,
    CensusMixin,
    BrainMixin,
):
    def __init__(
        self,
        host: str,
        port: int,
        team: str,
        frequency: Optional[int],
        verbose: bool = False,
    ):
        # Per-action stderr logging costs milliseconds/action (file-write
        # syscalls), which at high f exceeds the 7/f s budget per action and
        # starves the bot. Off by default; -v re-enables for debugging.
        self.verbose = verbose
        self.host = host
        self.port = port
        self.team = team
        self.frequency_override = frequency
        self.frequency = max(1, frequency or 100)
        self.sock: Optional[socket.socket] = None
        self.recv_buffer = ""
        self.blocking_buffer: List[str] = []
        # Outstanding commands awaiting a reply, FIFO (server answers in order).
        # The server buffers up to MAX_COMMAND_QUEUE=10 per client and silently
        # drops the overflow, so we cap below that. Pipelining deterministic
        # command sequences (movement plans) keeps the server's action queue full
        # instead of going idle for a round-trip between every action.
        # (cmd, sent_at, queue_depth_at_send). queue_depth lets us discard
        # samples taken behind a backed-up pipeline (their latency includes the
        # wait for earlier commands, not just their own execution).
        self.pending: List[Tuple[str, float, int]] = []
        self.max_pending = 8

        # Passive frequency tracking. The server time unit can change mid-game
        # (the GUI lets an operator retune it), and every timeout/cooldown here
        # is scaled by self.frequency -- a stale value silently breaks command
        # wedge detection and gather/incant timers. Instead of re-running the
        # active probe (8 round trips + real Forwards that move the bot), we
        # infer freq from the latency of commands we already send: freq in
        # ticks/s ~= tick_cost / real_elapsed. EMA-smoothed, override wins.
        self.cmd_tick_cost = {
            "Forward": 7,
            "Right": 7,
            "Left": 7,
            "Look": 7,
            "Inventory": 1,
            "Connect_nbr": 0,
            "Eject": 7,
            "Fork": 42,
            "Incantation": 300,
        }
        self.freq_ema: Optional[float] = None
        # Set when a command is wedge-dropped (reply<->command FIFO broken),
        # cleared once the pipeline drains empty. Pauses freq sampling meanwhile.
        self.pipeline_desynced = False
        self.memory = Memory()
        self.state = State.LOOK
        self.running = True
        self.bot_id = (
            int(time.time() * 1000000) + random.randint(0, 99999)
        ) % 1000000000
        self.plan: List[str] = []
        self.stones_to_drop: List[str] = []
        self.preparing_incantation = False
        self.waiting_incantation = False

        # NOTE: level-scaled survival was tried (survive_per_level=6) and REGRESSED
        # (0 L4, more deaths): the food economy is the binding constraint, so a
        # higher floor just makes high-level bots farm endlessly and never reach
        # the food to start a gather. Kept flat. The scaling hook stays at 0 in
        # case a richer map / food strategy later makes it viable.
        self.survive_food = 8
        self.survive_per_level = 0
        self.fork_food = 25
        # Fork discipline: fewer mouths on a food-scarce map. Each bot forks at
        # most this many times, and only while low-level (see should_fork) — a
        # swarm of starving babies drains the shared food the valuable high-level
        # bots need. This lean setting (3 forks, level<=2 only) is the LOW-death
        # config that reached level 8 (game win) in ~16 min at f=1000: low
        # attrition lets the cohort persist and climb. Looser settings churned
        # more bots and starved the high-level pool.
        self.max_forks = 3
        self.max_plan_length = 2 if self.frequency >= 100 else 3

        self.must_fork_after_gather_fail = False

        self.active_req: Optional[str] = None
        self.active_level = 0
        self.active_need = 0
        self.active_acks: Dict[int, float] = {}
        self.gather_counter = 0
        self.gather_attempts = 0
        self.gather_started_at = 0.0
        self.gather_last_broadcast_at = 0.0
        self.gather_arrival_started_at = 0.0
        self.last_gather_giveup_at = 0.0

        self.answered_reqs: Dict[str, float] = {}
        self.pending_ack_req: Optional[str] = None
        self.pending_ack_level = 0
        self.pending_ack_leader: Optional[int] = None

        # Level-verified physical arrival. Look shows "player" with NO level, so a
        # leader can't tell a same-level teammate from a passing level-1 baby. A
        # follower instead knows it's on the leader's exact tile when the leader's
        # broadcast arrives as bearing 0 (server-authoritative), and announces
        # ARRIVED. The leader counts distinct same-level ARRIVED senders and only
        # incants on THAT count — never the level-blind on-tile player count.
        self.arrived_at_leader: set = set()

        self.following_req: Optional[str] = None
        self.following_leader: Optional[int] = None
        self.following_until = 0.0
        self.pending_follow_direction: Optional[int] = None

        # Freeze-on-tile handshake: a leader with enough players broadcasts HOLD,
        # teammates freeze in place through its Set+Incantation ritual instead of
        # wandering off (which drops the count below the requirement -> ko).
        self.arrived_hold_until = 0.0
        self.incant_hold_broadcasts = 0

        # Manifest blitz strategy — the ONLY strategy. Every bot races to collect
        # the FULL stone set for L2->L8 (sum of all levels' requirements). The first
        # to complete becomes the anchor, the team banks food, synchronises,
        # converges on full tanks, drops all stones at once, and incants straight up
        # L2->L8 (each ritual consumes only its level's stones; all 6 players level
        # each time). Measured: ~30s to L8 and 4/4 win rate, robust across
        # 10x10..40x40 maps at reserve~200. Needs ~6 reachable mates; with fewer it
        # waits out manifest_timeout then sets manifest_gave_up and plays the simple
        # per-level gather as a last-resort safety (NOT a user-selectable mode).
        self.blitzing = False  # anchor mid-blitz (incant repeatedly)
        self.manifest_gave_up = False  # fell back to normal play (no anchor emerged)
        self.manifest_started_at = time.time()
        # Phased rendezvous: collect -> bank -> ready -> converge -> blitz. Bots
        # bank food to a reserve BEFORE converging and only launch once all are
        # ready, so the whole cohort makes the trek on full tanks (the fix for the
        # food-vs-convergence wall).
        self.manifest_phase = "collect"  # collect|bank|ready|converge (anchor: +blitz)
        self.manifest_is_anchor = False
        self.manifest_anchor = None  # id of the anchor a member is rallying to
        self.ready_too: set = set()  # anchor: members who signalled READY_TOO
        # Bank a big food reserve before converging so the cohort can outlast the
        # slow oscillating rally — this is the load-bearing tuning. At ~8 food/sec
        # drain, reserve/8 ≈ seconds of hold time, so 200 ≈ 25s, enough for 6 to
        # assemble. 200 is near-optimal across map sizes; higher just wastes
        # foraging time (40x40 @400 was slower for no gain). Tune via ZAPPY_RESERVE.
        self.food_reserve = int(os.environ.get("ZAPPY_RESERVE", "200"))
        self.food_abort = max(12, self.food_reserve // 3)  # re-bank below this
        self.manifest_food_floor = max(20, self.food_reserve // 2)  # collector top-up
        self.last_focus_bcast = 0.0
        self.last_ready_bcast = 0.0

        # ---- Opening census + fork election --------------------------------
        # The blitz needs >= census_target reachable mates, but a bot can't ask
        # the server its team size. So each bot announces presence once it boots
        # (HELLO:from=id) and everyone unions the ids into team_members. The
        # lowest known id is the elected forker: ONLY it forks, past the normal
        # per-bot cap, until the union reaches the quorum. The observed member
        # count is the global limiter -> total forks ~= quorum - initial bots.
        # Forked children (and late siblings) HELLO on boot and join the union;
        # their ids are time-seeded and larger, so they never win the election.
        # HELLO doubles as a permanent heartbeat: members silent past
        # member_ttl() are evicted (death sends no broadcast), which breaks the
        # quorum again and re-arms the census so the team refills to target.
        self.team_members = {self.bot_id}
        self.team_last_seen: Dict[int, float] = {}
        self.census_target = int(os.environ.get("ZAPPY_TEAM_TARGET", "6"))
        # Floor for the census window; the effective window is census_window(),
        # which scales with frequency (3000/f) so slow games get time to fork.
        self.census_timeout = float(os.environ.get("ZAPPY_CENSUS_TIMEOUT", "30"))
        # Settle window: wait for existing members' HELLOs to land before acting
        # as forker, so a freshly booted bot doesn't fork while it still thinks
        # it's alone (a singleton is always its own min).
        self.census_settle = float(os.environ.get("ZAPPY_CENSUS_SETTLE", "3"))
        # How long to wait for a forked child to announce before forking again
        # (a deadbeat child shouldn't stall the census).
        self.census_child_timeout = float(os.environ.get("ZAPPY_CENSUS_CHILD", "4"))
        self.census_deadline: Optional[float] = None
        self.census_settle_until: Optional[float] = None
        self.census_fork_deadline = 0.0
        self.last_hello_at = 0.0


# ---- shims.py ----------------------------------------------------------

"""Compatibility shims for train_ai/train_rl: NetworkClient, Parser.

Unchanged from the original; not used by the live bot."""




INCANTATION_REQUIREMENTS = REQ


class NetworkClient:
    def __init__(self, host: str, port: int, team_name: str):
        self.host = host
        self.port = port
        self.team_name = team_name
        self.sock: Optional[socket.socket] = None
        self.recv_buffer = ""
        self.blocking_buffer: List[str] = []

    def connect(self) -> None:
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.connect((self.host, self.port))
        self.sock.setblocking(False)

    def close(self) -> None:
        if self.sock is not None:
            try:
                self.sock.close()
            finally:
                self.sock = None

    def send_line(self, line: str) -> None:
        if self.sock is None:
            raise RuntimeError("socket not connected")

        if not line.endswith("\n"):
            line += "\n"

        self.sock.sendall(line.encode())

    def read_available_lines(self) -> List[str]:
        if self.sock is None:
            return []

        out: List[str] = []

        while True:
            readable, _, _ = select.select([self.sock], [], [], 0)

            if not readable:
                break

            try:
                data = self.sock.recv(4096)
            except BlockingIOError:
                break
            except ConnectionResetError:
                out.append("dead")
                break

            if not data:
                out.append("dead")
                break

            self.recv_buffer += data.decode(errors="ignore")

            while "\n" in self.recv_buffer:
                line, self.recv_buffer = self.recv_buffer.split("\n", 1)
                out.append(line.strip())

        return out

    def read_blocking_line(self, timeout: float = 5.0) -> str:
        if self.blocking_buffer:
            return self.blocking_buffer.pop(0)

        start = time.time()

        while time.time() - start < timeout:
            lines = self.read_available_lines()

            if lines:
                self.blocking_buffer.extend(lines)
                return self.blocking_buffer.pop(0)

            time.sleep(0.005)

        raise TimeoutError("timeout waiting server")

    def drain_blocking_buffer(self) -> List[str]:
        lines = self.blocking_buffer[:]
        self.blocking_buffer.clear()
        return lines


class Parser:
    @staticmethod
    def parse_inventory(line: str) -> Dict[str, int]:
        inv = {r: 0 for r in RESOURCES}
        clean = line.strip()

        if clean.startswith("["):
            clean = clean[1:]

        if clean.endswith("]"):
            clean = clean[:-1]

        for part in clean.split(","):
            toks = part.strip().split()

            if len(toks) == 2 and toks[0] in inv:
                try:
                    inv[toks[0]] = int(toks[1])
                except ValueError:
                    inv[toks[0]] = 0

        return inv

    @staticmethod
    def parse_look(line: str) -> List[List[str]]:
        clean = line.strip()

        if clean.startswith("["):
            clean = clean[1:]

        if clean.endswith("]"):
            clean = clean[:-1]

        return [tile.strip().split() for tile in clean.split(",")]

    @staticmethod
    def is_inventory_response(line: str) -> bool:
        if not (line.startswith("[") and line.endswith("]")):
            return False

        clean = line[1:-1].strip()

        if not clean:
            return False

        for part in clean.split(","):
            toks = part.strip().split()

            if len(toks) != 2:
                return False

            if toks[0] not in RESOURCES:
                return False

            if not toks[1].isdigit():
                return False

        return True

    @staticmethod
    def is_look_response(line: str) -> bool:
        return (
            line.startswith("[")
            and line.endswith("]")
            and not Parser.is_inventory_response(line)
        )

    @staticmethod
    def parse_broadcast(line: str) -> Optional[Tuple[int, str]]:
        if not line.startswith("message "):
            return None

        try:
            prefix, text = line.split(",", 1)
            return int(prefix.replace("message", "").strip()), text.strip()
        except ValueError:
            return None

    @staticmethod
    def parse_current_level(line: str) -> Optional[int]:
        if not line.startswith("Current level:"):
            return None

        try:
            return int(line.replace("Current level:", "", 1).strip())
        except ValueError:
            return None


# ---- cli.py ------------------------------------------------------------

"""Command-line entry point: arg parsing + main()."""




def _usage() -> str:
    return (
        f"UTILISATION : {sys.argv[0]} -p port -n nom -h machine [-f freq] [-v]\n"
        "  -p port     numéro de port du serveur (obligatoire)\n"
        "  -n nom      nom de l'équipe (obligatoire)\n"
        "  -h machine  adresse du serveur (par défaut : localhost)\n"
        "  -f freq     fréquence : unités de temps par seconde (strictement positive)\n"
        "  -v          journalise chaque commande/réponse (lent ; désactivé par défaut)\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-p", dest="port", type=int)
    parser.add_argument("-n", dest="name")
    parser.add_argument("-h", dest="host", default="localhost")
    parser.add_argument("-f", dest="frequency", type=int, default=None)
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="log every command/response (slow; off by default)",
    )
    parser.add_argument("--help", action="store_true")

    args, unknown = parser.parse_known_args()

    if args.help:
        print(_usage())
        raise SystemExit(0)

    errors = []
    if unknown:
        errors.append("arguments inconnus : " + " ".join(unknown))
    missing = [flag for flag, value in (("-p", args.port), ("-n", args.name)) if value is None]
    if missing:
        errors.append("argument(s) requis manquant(s) : " + " ".join(missing))
    if args.port is not None and (args.port <= 0 or args.port > 65535):
        errors.append("port invalide : doit être entre 1 et 65535")
    if args.frequency is not None and args.frequency <= 0:
        errors.append("fréquence invalide : doit être strictement positive")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        print(_usage(), file=sys.stderr, end="")
        raise SystemExit(84)

    return args


def main() -> int:
    try:
        args = parse_args()
        return AI(args.host, args.port, args.name, args.frequency, args.verbose).run()
    except KeyboardInterrupt:
        print("[IA] Interrompu", file=sys.stderr)
        return 130
    except Exception as err:
        print(f"[IA] Erreur : {err}", file=sys.stderr)
        return 84


if __name__ == "__main__":
    raise SystemExit(main())

